### ISSUE TITLE
Compilation for Lazarus / Free Pascal?

### ISSUE THREAD

**Issue by casper** [monde-sistemas/pusher-websocket-delphi#4]
Hi. Is there any way to get this library to work on Lazarus / Free Pascal?

I got most things to compile, but this line in `PusherClient.pas` seems to be a show stopper:

```
  TCallbackProcedure = reference to procedure(message: string);
```
Is there any way to implement something similar that would work in FPC?

**Comment by fabioxgn** [comment]
Hi @casper thanks for the interest in our project.

We don´t currently use Lazarus so we have no plans of supporting it, but we would be happy to merge your Pull Request. If this is important to you, please send us a PR.

Thanks.

**Comment by esasse** [comment]
The repository will be archived.
