### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by randomd00d** [monde-sistemas/pusher-websocket-delphi#5]
I realize that the project may very well be dead, but I was wondering if there's a built-in TLS support in your client? I've been using WireShark to monitor connections, and all I'm getting are unencrypted WebSocket connections.

**Comment by RobertoSchneiders** [comment]
Yes, the project is dead. This is just a wrapper around the .net library, so, it should be able to support secure connections. I think SSL is enabled by default. It's probably better to use the https://github.com/pusher-community/pusher-websocket-dotnet directly.

**Comment by randomd00d** [comment]
Ah, OK. Thanks for the quick heads up.
